### ISSUE TITLE
"patch" is not recognized on windows

### ISSUE THREAD

**Issue by marcomd** [cowboyd/libv8#203] opened 2016-01-04 18:01 UTC
I'm using 3.16.14.13 to combine with therubyracer gem but i also tried last version with the same result.

```
"patch" is not recognized as an internal or external command
```

C:/ruby/ruby-223x64p173/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.13/ext/libv8/patcher.rb:51:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)

**Comment by ignisf** [comment] 2016-01-04 18:55
Hello,

The build process requires the `patch` utility to be present in the PATH. Could you please take a look if it is in the Ruby DevKit?

**Comment by marcomd** [comment] 2016-01-05 10:40
Hello,

no there isn't in the dev kit, i put it manually but i get an error. I'm investigating

```
C:\>gem install libv8 -v=3.16.14.13
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
        ERROR: Failed to build gem native extension.

    current directory: C:/ruby/ruby-223x64p173/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.13/ext/libv8
C:/ruby/ruby-223x64p173/bin/ruby.exe -r ./siteconf20160105-8628-w64lvc.rb extconf.rb
creating Makefile
Assertion failed: hunk, file ../patch-2.5.9-src/patch.c, line 354

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
C:/ruby/ruby-223x64p173/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.13/ext/libv8/patcher.rb:51:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)
        from C:/ruby/ruby-223x64p173/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.13/ext/libv8/patcher.rb:49:in `each'
```

**Comment by marcomd** [comment] 2016-01-07 09:06
http://gnuwin32.sourceforge.net/packages/patch.htm

I found this note:
*On MS-Windows, the patchfile must be a text file, i.e. CR-LF must be used as line endings. A file with LF may give the error: "Assertion failed, hunk, file patch.c, line 343," unless the option '--binary' is given.*

**Comment by marcomd** [comment] 2016-01-07 10:41
I suggest:

```ruby
`patch -p1 -N < #{patch}#{' --binary' if RUBY_PLATFORM =~ /mingw/}`
```

**Comment by marcomd** [comment] 2016-01-07 11:05
I updated the file patcher.rb locally and i run extconf.rb. It went to the end without errors but it did not create the binary

```
C:\ruby\ruby-223x64p173\lib\ruby\gems\2.2.0\gems\libv8-3.16.14.13\ext\libv8>ruby extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.8
Using compiler: C:\ruby\DevKit-472x64\mingw\bin\c++.EXE (GCC version 4.7.2)
find: `out': No such file or directory
GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=ia32 \
                      -S.ia32  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=x64 \
                      -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
Patching out/build/All.target.ia32.mk...
...
```

**Comment by ignisf** [comment] 2016-01-07 11:15
First of all, great work.

Second, I do not see an error message in your latest comment. How did you determine it did not compile the library?

**Comment by marcomd** [comment] 2016-01-07 11:53
Thanks but it is only a small contribution, you are doing a great work.

I'm not sure it worked because i don't find the binary in the libv8-3.16.14.13\vendor\v8\out
```
<DIR>          build
<DIR>          preparser
<DIR>          samples
<DIR>          src
<DIR>          tools
<DIR>          x64.release
           182 environment
         7.206 gyp-win-tool
        15.907 Makefile.ia32
        18.091 Makefile.x64
```

I expected to find somewhere the .so file that is normally located in the folder under ..\extensions\x64-mingw32\2.2.0\libv8-3.16.14.13

**Comment by ignisf** [comment] 2016-01-07 12:00
The scripts compile a static library, so you should be looking for a `.a` file instead of a `.so` (though I'm not sure that this is the suffix for static libraries compiled by MinGW). You can try to produce a binary gem directly by running `rake binary`.

**Comment by marcomd** [comment] 2016-01-07 13:05
I cloned the repo but compiling goes wrong. A puts shows thats the patch is `disable-building-tests.patch`

```
C:\Marco\Progetti\Ruby\Gems\libv8>rake binary
ruby ext/libv8/extconf.rb
creating Makefile
patch -p1 -N < C:/Marco/Progetti/Ruby/Gems/libv8/patches/disable-building-tests.patch --binary
C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/patcher.rb:53:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/patcher.rb:49:in `each'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/patcher.rb:49:in `block in patch!'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/patcher.rb:45:in `open'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/patcher.rb:45:in `patch!'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/builder.rb:57:in `block in build_libv8!'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/builder.rb:52:in `chdir'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/builder.rb:52:in `build_libv8!'
        from C:/Marco/Progetti/Ruby/Gems/libv8/ext/libv8/location.rb:24:in `install!'
        from ext/libv8/extconf.rb:7:in `<main>'
rake aborted!
Command failed with status (1): [ruby ext/libv8/extconf.rb...]
C:/Marco/Progetti/Ruby/Gems/libv8/Rakefile:25:in `block in <top (required)>'
Tasks: TOP => binary => compile
```

**Comment by ignisf** [comment] 2016-01-07 13:15
Hmmm.. Can you check if the patch is actually applied? If it is, there is probably an issue with the evaluation of the return code of the patch command.

**Comment by marcomd** [comment] 2016-01-07 15:52
Ok It seems to work, there is a libv8-3.16.14.14-x64-mingw32.gem (i added +1 to version to avoid confusion) under /pkg folder. I installed and I would to test it. I'm installing therubyracer but i get an error, damn

**Comment by ignisf** [comment] 2016-01-07 16:34
Great! Could you open a PR with your changes up until now?

**Comment by mnuzzolilo** [comment] 2016-03-24 22:36
There seems to be far more problems with this builder file on Windows than simply lack of the patch executable.
Fetch v8 fails to execute, without much of an error message.  Fetch v8 hangs when I run it manually. 

I have to be honest with you, this is the most frustrating experience I have ever had with a library installation, and that's saying something.

**Comment by mnuzzolilo** [comment] 2016-03-25 00:37
So this patch thing is a straightforward fix 

1. Make sure you actually are testing this on Windows yourself. Don't expect the "community" to submit a pull on this. Chances are if we've had this problem we've already wasted countless hours of time and won't have the patience or time to spare any more of it.

2. Include a version of patch.exe which will work on windows

3. When running a patch, if the environment is windows, replace all LF characters in the .patch file with CRLF, and use --binary as a command line suffix for patch.exe

**Comment by ignisf** [comment] 2016-03-25 02:25
Hi @mnuzzolilo,

First, thank you for your feedback!

Second, I very much understand your frustration. We've been dealing with the peculiarities of the upstream v8 build system for years now.

Now to address the issues you are raising:

1. My views are that if this bug is not worth the time of anybody in the community that actually uses Windows, it's not worth my time either. Not to mention I don't even own Windows and I have absolutely zero experience with Ruby, MinGW or any kind of development in Windows and its idiosyncrasies.

2. I very much dislike the idea of shipping binaries with the gem that I consider belong to the SDK. What I've been thinking about is using a library that implements the patch functionality but is platform independent. I have not come across anything suitable yet.

3. I'd be thankful if you considered submitting a PR that implements these changes.

**Comment by mnuzzolilo** [comment] 2016-03-25 02:51
. Submitting a PR means I have to 

1. Clean everything up
2. Figure out how to make my changes generic enough so that it can work on anyone's machine
3. Brace myself for complaints if something goes wrong

Like I said, I've already lost at least 6 hours to this problem, and I wouldn't even be here if it wasn't for the fact that running rails on Windows for projects that use CSS Less has a dependency here.  Developers who have this use case often are on the clock, and have to meet deadlines.  If I've already lost this amount of time, then I'm already in the hole when it comes to meeting that deadline.  

I feel like I've been more than generous by giving you step by step guidelines on how to solve this issue, and you know the project better than I do and therefore can formulate an appropriate fix for it.  What you do from there isn't of my concern, your project is what you make it.

**Comment by ignisf** [comment] 2016-03-25 03:08
There is an ongoing discussion about adding `patch` to the Ruby DevKit, see https://github.com/oneclick/rubyinstaller/pull/222

**Comment by ignisf** [comment] 2016-03-25 03:10
@mnuzzolilo, again, thank you for your input and good luck with your project.

**Comment by mnuzzolilo** [comment] 2016-03-25 22:25
@ignisf thank you for the info. I've decided to take a second look at this and was able to make a lot more progress. I'm going to submit a pull request when I can.  The 3.x branch (currently master) is confirmed to not work on Windows as v8 itself has compile errors (which are presumably fixed in a later version).

**Comment by mnuzzolilo** [comment] 2016-03-26 08:16
patch.exe is already included in the latest version of depot_tools.  I will be able to have a fix for this eventually. However, other problems are causing build failures on windows for version 4.x, and it is no small mess either.  It's mostly an issue of version mismatches. 

On another note I believe you may have ran into a problem with make out/Makefile.ia32 generating an error. I was able to output some detailed debugging information and find that the correct usage is to replace Makefile.ia32 with Makefile.ia32.release (or debug). Will have more later.

**Comment by marcomd** [comment] 2016-03-29 08:20
I do not think I'll have any more time to spend, sorry for not having completed the PR but faced with that errors I can do nothing.

@mnuzzolilo
Complaining is a waste of time, you can give your contribution :+1:

**Comment by mnuzzolilo** [comment] 2016-03-29 18:35
I'll get it in when I can @marcomd, thanks :)

**Comment by mnuzzolilo** [comment] 2016-03-29 19:54
P.S. @marcomd If you want to see what I have so far I can set up another branch/fork and you can take it from there if you want

**Closed** 2018-07-06 08:31 UTC
Labels: os: windows, type: upstream issue
