### ISSUE TITLE
Failed to install on macOS High Sierra

### ISSUE THREAD

**Issue by sergey-alekseev** [cowboyd/libv8#248] opened 2017-10-10 13:19 UTC
[The full gem install trace](https://gist.github.com/sergey-alekseev/b4c44003086ce8ab68fd99d673f62129).
```
$ gem install libv8 -v '5.9.211.38.1'
...

Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 299, in <module>
    sys.exit(main())
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 294, in main
    return run(options, spec, root)
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 288, in run
    return checkout.init()
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 131, in init
    self.run_gclient(*sync_cmd)
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/vendor/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
  from /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:115:in `chdir'
  from /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
  from /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/ext/libv8/builder.rb:71:in `build_libv8!'
  from /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/gems/libv8-5.9.211.38.1/ext/libv8/location.rb:24:in `install!'
  from extconf.rb:7:in `<main>'

extconf failed, exit code 1
```

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.14
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/sergey/.rvm/gems/ruby-2.4.2@gemset
  - USER INSTALLATION DIRECTORY: /Users/sergey/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /Users/sergey/.rvm/rubies/ruby-2.4.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/bin
  - SPEC CACHE DIRECTORY: /Users/sergey/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/sergey/.rvm/rubies/ruby-2.4.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/sergey/.rvm/gems/ruby-2.4.2@gemset
     - /Users/sergey/.rvm/gems/ruby-2.4.2@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/sergey/.rvm/gems/ruby-2.4.2@gemset/bin
     - /Users/sergey/.rvm/gems/ruby-2.4.2@global/bin
     - /Users/sergey/.rvm/rubies/ruby-2.4.2/bin
     - /Users/sergey/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/Postgres.app/Contents/Versions/latest/bin
     - /Users/sergey/bin
```

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by SamSaffron** [comment] 2017-10-12 01:55
@ignisf this looks pretty urgent... we got to sort it out.

**Comment by SamSaffron** [comment] 2017-10-12 02:00
Yeah we need a Darwin 17 binary build ... at the moment there is none :(

**Comment by cowboyd** [comment] 2017-10-12 14:10
OSX has always been a problem for us because of the poor virtualization story. It means that a developer needs to upgrade their computer just to build libv8. For example, I'm just on regular Sierra.

**Comment by douglas** [comment] 2017-10-12 15:11
Hello!

I built the libv8 gem for High Sierra and you can use it until there is a official release =)

https://drive.google.com/file/d/0B6oB9XcIPsNTYkxWWTlXX1c1eEE/view?usp=sharing

To install it, follow this steps:

1. Download it to your home (~)
2. gem install ~/libv8-5.9.211.38.1-x86_64-darwin-17.gem
3. Profit =)

Here are the steps to build and generate the libv8 v5.9.211.38.1 binary gem for High Sierra
— Credits to: @mangoov for the howto on building libv8

1. Clone the libv8 repo to you home (~): `git clone --recursive git://github.com/cowboyd/libv8.git`
2. cd `~/libv8` and then `git checkout v5.9.211.38.1`
3. `cd vendor/v8`
4. `git checkout 5.9.211.38`
5.` cd -` and edit `builder.rb`
6. replace `setup_build_deps!` in `~/libv8/ext/libv8/builder.rb` with
```python
def setup_build_deps!
  ENV['PATH'] = "#{File.expand_path('../../../vendor/depot_tools', __FILE__)}:#{ENV['PATH']}"
  Dir.chdir(File.expand_path('../../../vendor/v8', __FILE__)) do
    unless system "git checkout #{source_version}"
      fail "unable to checkout source for v8 #{source_version}"
    end
    system "env #{gyp_defines} gclient sync -n" or fail "could not sync v8 build dependencies"
    system "git checkout Makefile" # Work around a weird bug on FreeBSD
  end
end
```
6. `run bundle install`
7. copy the .gclient and .gclient_entries from [this link](https://drive.google.com/drive/folders/0B6oB9XcIPsNTaXpCbHFTcmVqbzQ?usp=sharing) and put them in `~/libv8/vendor/`
8. Execute `bundle exec rake compile`
9. To generate the binary gem: `bundle exec rake binary`
10. You will have the gem in `~/libv8/pkg`.
11. Just need to install it with the command: `gem install ~/libv8/pkg/libv8-5.9.211.38.1-x86_64-darwin-17.gem`
```

**Comment by douglas** [comment] 2017-10-12 15:29
Btw, I'm building the binaries for v6.0.286.54.1 and I will upload the binary as soon as it finishes here.

I'm using the following steps to build it:

1. `cd ~`
2. `git clone --recursive git://github.com/cowboyd/libv8.git`
3. `git checkout -b v6.0.286.54.1`
4. `bundle install`
5. `bundle exec rake compile`
6. `bundle exec rake binary`

Hope it helps =)

**Comment by douglas** [comment] 2017-10-12 16:03
Here is the binary for 6.0.286.54.1:

https://drive.google.com/file/d/0B6oB9XcIPsNTTmhNTEYzWXVDc2c/view?usp=sharing

To install it follow these steps:

1. Download it to your home (~)
2. gem install ~/libv8-6.0.286.54.1-x86_64-darwin-17.gem
3. Profit!

HTH =)

**Comment by ignisf** [comment] 2017-10-12 16:06
PSA Be mindful when trusting your and your client's data to random people's binaries.

**Comment by douglas** [comment] 2017-10-12 16:11
Totally true, @ignisf!

That is why I posted the steps I used to build the binaries so people can build it themselves (if they want) until we have the official ones.

Btw, thanks for all the work in libv8! Thanks for generating the binaries so we don't have to deal with compiling v8 every time as it takes a long time here.

**Comment by SamSaffron** [comment] 2017-10-12 22:21
@cowboyd vmware is quite good these days when it comes to virtualizing osx, I have high sierra working in vmware on windows (with unlocker), mac is even easier.

**Comment by sergey-alekseev** [comment] 2017-10-13 08:01
@Douglas thank you very much for [providing the binary](https://github.com/cowboyd/libv8/issues/248#issuecomment-336168126)!

**Comment by sshaw** [comment] 2017-10-14 00:48
I get this error on OS X 10.9.5 (and on my work box, which is 10.10  -I think) but only on versions of Ruby greater than 2.1.

**Comment by SamSaffron** [comment] 2017-10-17 03:22
@cowboyd @ignisf any chance I can have push on the the gem? I can try to get this out there.

**Comment by ignisf** [comment] 2017-10-23 20:18
@SamSaffron, @cowboyd has admin access to Rubygems.

**Comment by ignisf** [comment] 2017-10-23 20:19
Duplicate of #246

**Closed** 2017-10-23 21:48 UTC
Labels: os: osx

**Comment by ajsharp** [comment] 2018-01-19 07:14
I was able to solve by bumping to a new version
