### ISSUE TITLE
Problem with building 5.3.332.38.5

### ISSUE THREAD

**Issue by jdongelmans** [cowboyd/libv8#251] opened 2017-10-31 10:43 UTC
I'm trying to update my base image when I encountered this error which was previously absent (looks a bit similar like https://github.com/cowboyd/libv8/issues/250).

Running on Alpine `3.6`:
```
export GYP_DEFINES= linux_use_bundled_binutils=0 linux_use_bundled_gold=0
gem install --verbose libv8-5.3.332.38.5-x86_64-linux.gem
```
```
Building native extensions.  This could take a while...
current directory: /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8
/usr/local/bin/ruby -r ./siteconf20171031-124-1nulnnt.rb extconf.rb
creating Makefile
Running: gclient root

v8 (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/_gclient_v8_jW7h1h' in '/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor'
[0:00:00] Cloning into '/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/_gclient_v8_jW7h1h'...
[0:00:02] remote: Sending approximately 488.47 MiB ...
[0:00:03] remote: Counting objects: 1
[0:00:04] remote: Counting objects: 64670, done
[0:00:04] remote: Finding sources:  20% (1/5)
[0:00:04] remote: Finding sources: 100% (5/5)
[0:00:04] Receiving objects:   0% (1/503044)
[0:00:05] Receiving objects:   5% (25153/503044), 9.44 MiB | 9.44 MiB/s
[0:00:06] Receiving objects:  10% (50305/503044), 17.73 MiB | 8.86 MiB/s
[0:00:07] Receiving objects:  14% (70427/503044), 26.98 MiB | 8.99 MiB/s
[0:00:08] Receiving objects:  19% (95579/503044), 37.13 MiB | 9.28 MiB/s
[0:00:09] Receiving objects:  24% (120731/503044), 50.49 MiB | 9.12 MiB/s
[0:00:10] Receiving objects:  28% (140853/503044), 58.61 MiB | 9.08 MiB/s
[0:00:11] Receiving objects:  33% (166005/503044), 67.79 MiB | 9.07 MiB/s
[0:00:12] Receiving objects:  43% (216309/503044), 77.10 MiB | 8.88 MiB/s
[0:00:14] Receiving objects:  53% (271074/503044), 86.68 MiB | 8.91 MiB/s
[0:00:15] Receiving objects:  54% (272209/503044), 101.32 MiB | 9.49 MiB/s
[0:00:17] Receiving objects:  56% (285789/503044), 119.83 MiB | 9.50 MiB/s
[0:00:19] Receiving objects:  57% (289959/503044), 133.75 MiB | 9.32 MiB/s
[0:00:21] Receiving objects:  58% (294526/503044), 151.88 MiB | 9.15 MiB/s
[0:00:23] Receiving objects:  58% (296452/503044), 164.44 MiB | 7.81 MiB/s
[0:00:24] Receiving objects:  60% (301827/503044), 179.00 MiB | 7.77 MiB/s
[0:00:26] Receiving objects:  60% (306592/503044), 192.25 MiB | 8.05 MiB/s
[0:00:27] Receiving objects:  62% (311888/503044), 211.27 MiB | 9.37 MiB/s
[0:00:29] Receiving objects:  63% (318745/503044), 220.15 MiB | 9.09 MiB/s
[0:00:31] Receiving objects:  64% (325019/503044), 240.66 MiB | 9.64 MiB/s
[0:00:32] Receiving objects:  65% (327183/503044), 249.33 MiB | 9.61 MiB/s
[0:00:33] Receiving objects:  66% (332010/503044), 267.05 MiB | 9.06 MiB/s
[0:00:35] Receiving objects:  67% (338416/503044), 277.35 MiB | 9.16 MiB/s
[0:00:36] Receiving objects:  69% (347101/503044), 290.84 MiB | 9.05 MiB/s
[0:00:38] Receiving objects:  70% (354249/503044), 306.37 MiB | 9.57 MiB/s
[0:00:39] Receiving objects:  71% (357162/503044), 315.41 MiB | 9.58 MiB/s
[0:00:40] Receiving objects:  72% (362192/503044), 328.06 MiB | 9.35 MiB/s
[0:00:41] Receiving objects:  73% (367223/503044), 338.36 MiB | 9.43 MiB/s
[0:00:43] Receiving objects:  74% (374244/503044), 350.86 MiB | 8.95 MiB/s
[0:00:44] Receiving objects:  75% (380121/503044), 359.31 MiB | 8.93 MiB/s
[0:00:45] Receiving objects:  77% (387344/503044), 377.02 MiB | 8.58 MiB/s
[0:00:47] Receiving objects:  77% (391135/503044), 386.26 MiB | 8.54 MiB/s
[0:00:48] Receiving objects:  78% (395336/503044), 394.88 MiB | 8.90 MiB/s
[0:00:50] Receiving objects:  79% (402327/503044), 410.58 MiB | 8.46 MiB/s
[0:00:51] Receiving objects:  80% (406387/503044), 418.30 MiB | 8.02 MiB/s
[0:00:52] Receiving objects:  82% (412497/503044), 427.00 MiB | 7.83 MiB/s
[0:00:53] Receiving objects:  84% (422557/503044), 441.58 MiB | 8.23 MiB/s
[0:00:54] Receiving objects:  88% (442679/503044), 451.27 MiB | 9.02 MiB/s
[0:00:55] Receiving objects:  91% (457771/503044), 460.57 MiB | 9.37 MiB/s
[0:00:56] Receiving objects:  94% (472862/503044), 473.91 MiB | 9.29 MiB/s
[0:00:58] Receiving objects:  97% (492962/503044), 483.54 MiB | 9.26 MiB/s
[0:00:58] remote: Total 503044 (delta 412776), reused 503042 (delta 412776)
[0:00:58] Receiving objects: 100% (503044/503044), 487.73 MiB | 9.26 MiB/s
[0:00:58] Resolving deltas:   0% (0/412776)
[0:00:59] Resolving deltas:   5% (22412/412776)
[0:01:00] Resolving deltas:  10% (41284/412776)
[0:01:01] Resolving deltas:  18% (74307/412776)
[0:01:02] Resolving deltas:  25% (103199/412776)
[0:01:03] Resolving deltas:  31% (131314/412776)
[0:01:04] Resolving deltas:  38% (158323/412776)
[0:01:05] Resolving deltas:  46% (190124/412776)
[0:01:07] Resolving deltas:  51% (210536/412776)
[0:01:08] Resolving deltas:  52% (217734/412776)
[0:01:09] Resolving deltas:  53% (220827/412776)
[0:01:11] Resolving deltas:  54% (226741/412776)
[0:01:13] Resolving deltas:  55% (227850/412776)
[0:01:14] Resolving deltas:  55% (230866/412776)
[0:01:15] Resolving deltas:  57% (235858/412776)
[0:01:16] Resolving deltas:  60% (247670/412776)
[0:01:18] Resolving deltas:  63% (260474/412776)
[0:01:19] Resolving deltas:  64% (264185/412776)
[0:01:21] Resolving deltas:  65% (270796/412776)
[0:01:22] Resolving deltas:  67% (276567/412776)
[0:01:23] Resolving deltas:  68% (280767/412776)
[0:01:25] Resolving deltas:  69% (284858/412776)
[0:01:26] Resolving deltas:  70% (292456/412776)
[0:01:27] Resolving deltas:  71% (295870/412776)
[0:01:28] Resolving deltas:  73% (301488/412776)
[0:01:29] Resolving deltas:  75% (309582/412776)
[0:01:31] Resolving deltas:  77% (317855/412776)
[0:01:32] Resolving deltas:  78% (324491/412776)
[0:01:33] Resolving deltas:  78% (325570/412776)
[0:01:34] Resolving deltas:  79% (329207/412776)
[0:01:35] Resolving deltas:  80% (330895/412776)
[0:01:37] Resolving deltas:  82% (338581/412776)
[0:01:38] Resolving deltas:  82% (340732/412776)
[0:01:40] Resolving deltas:  84% (346732/412776)
[0:01:41] Resolving deltas:  85% (352104/412776)
[0:01:42] Resolving deltas:  87% (359220/412776)
[0:01:43] Resolving deltas:  88% (363243/412776)
[0:01:44] Resolving deltas:  89% (367381/412776)
[0:01:45] Resolving deltas:  89% (370926/412776)
[0:01:48] Resolving deltas:  91% (376923/412776)
[0:01:49] Resolving deltas:  92% (379755/412776)
[0:01:50] Resolving deltas:  93% (383944/412776)
[0:01:51] Resolving deltas:  94% (389452/412776)
[0:01:52] Resolving deltas:  95% (392390/412776)
[0:01:54] Resolving deltas:  96% (396830/412776)
[0:01:55] Resolving deltas:  98% (404526/412776)
[0:01:57] Resolving deltas:  98% (408208/412776)
[0:01:58] Resolving deltas:  99% (411809/412776)
[0:01:58] Resolving deltas: 100% (412776/412776)
[0:02:12] From https://chromium.googlesource.com/v8/v8
[0:02:12]  * [new ref]               refs/branch-heads/0.1         -> branch-heads/0.1
[0:02:12]  * [new ref]               refs/branch-heads/0.3         -> branch-heads/0.3
[0:02:12]  * [new ref]               refs/branch-heads/1.1         -> branch-heads/1.1
[0:02:12]  * [new ref]               refs/branch-heads/1.2         -> branch-heads/1.2
[0:02:12]  * [new ref]               refs/branch-heads/1.3         -> branch-heads/1.3
[0:02:12]  * [new ref]               refs/branch-heads/2.0         -> branch-heads/2.0
[0:02:12]  * [new ref]               refs/branch-heads/2.1         -> branch-heads/2.1
[0:02:12]  * [new ref]               refs/branch-heads/2.2         -> branch-heads/2.2
[0:02:12]  * [new ref]               refs/branch-heads/2.3         -> branch-heads/2.3
[0:02:12]  * [new ref]               refs/branch-heads/2.4         -> branch-heads/2.4
[0:02:12]  * [new ref]               refs/branch-heads/2.5         -> branch-heads/2.5
[0:02:12]  * [new ref]               refs/branch-heads/3.0         -> branch-heads/3.0
[0:02:12]  * [new ref]               refs/branch-heads/3.1         -> branch-heads/3.1
[0:02:12]  * [new ref]               refs/branch-heads/3.10        -> branch-heads/3.10
[0:02:12]  * [new ref]               refs/branch-heads/3.11        -> branch-heads/3.11
[0:02:12]  * [new ref]               refs/branch-heads/3.12        -> branch-heads/3.12
[0:02:12]  * [new ref]               refs/branch-heads/3.13        -> branch-heads/3.13
[0:02:12]  * [new ref]               refs/branch-heads/3.14        -> branch-heads/3.14
[0:02:12]  * [new ref]               refs/branch-heads/3.15        -> branch-heads/3.15
[0:02:12]  * [new ref]               refs/branch-heads/3.16        -> branch-heads/3.16
[0:02:12]  * [new ref]               refs/branch-heads/3.17        -> branch-heads/3.17
[0:02:12]  * [new ref]               refs/branch-heads/3.18        -> branch-heads/3.18
[0:02:12]  * [new ref]               refs/branch-heads/3.19        -> branch-heads/3.19
[0:02:12]  * [new ref]               refs/branch-heads/3.2         -> branch-heads/3.2
[0:02:12]  * [new ref]               refs/branch-heads/3.20        -> branch-heads/3.20
[0:02:12]  * [new ref]               refs/branch-heads/3.20.15.5   -> branch-heads/3.20.15.5
[0:02:12]  * [new ref]               refs/branch-heads/3.21        -> branch-heads/3.21
[0:02:12]  * [new ref]               refs/branch-heads/3.22        -> branch-heads/3.22
[0:02:12]  * [new ref]               refs/branch-heads/3.23        -> branch-heads/3.23
[0:02:12]  * [new ref]               refs/branch-heads/3.24        -> branch-heads/3.24
[0:02:12]  * [new ref]               refs/branch-heads/3.25        -> branch-heads/3.25
[0:02:12]  * [new ref]               refs/branch-heads/3.26        -> branch-heads/3.26
[0:02:12]  * [new ref]               refs/branch-heads/3.27        -> branch-heads/3.27
[0:02:12]  * [new ref]               refs/branch-heads/3.28        -> branch-heads/3.28
[0:02:12]  * [new ref]               refs/branch-heads/3.29        -> branch-heads/3.29
[0:02:12]  * [new ref]               refs/branch-heads/3.3         -> branch-heads/3.3
[0:02:12]  * [new ref]               refs/branch-heads/3.30        -> branch-heads/3.30
[0:02:12]  * [new ref]               refs/branch-heads/3.31        -> branch-heads/3.31
[0:02:12]  * [new ref]               refs/branch-heads/3.4         -> branch-heads/3.4
[0:02:12]  * [new ref]               refs/branch-heads/3.5         -> branch-heads/3.5
[0:02:12]  * [new ref]               refs/branch-heads/3.6         -> branch-heads/3.6
[0:02:12]  * [new ref]               refs/branch-heads/3.7         -> branch-heads/3.7
[0:02:12]  * [new ref]               refs/branch-heads/3.8         -> branch-heads/3.8
[0:02:12]  * [new ref]               refs/branch-heads/3.9         -> branch-heads/3.9
[0:02:12]  * [new ref]               refs/branch-heads/4.1         -> branch-heads/4.1
[0:02:12]  * [new ref]               refs/branch-heads/4.2         -> branch-heads/4.2
[0:02:12]  * [new ref]               refs/branch-heads/4.2.39      -> branch-heads/4.2.39
[0:02:12]  * [new ref]               refs/branch-heads/4.3         -> branch-heads/4.3
[0:02:12]  * [new ref]               refs/branch-heads/4.4         -> branch-heads/4.4
[0:02:12]  * [new ref]               refs/branch-heads/4.5         -> branch-heads/4.5
[0:02:12]  * [new ref]               refs/branch-heads/4.6         -> branch-heads/4.6
[0:02:12]  * [new ref]               refs/branch-heads/4.7         -> branch-heads/4.7
[0:02:12]  * [new ref]               refs/branch-heads/4.8         -> branch-heads/4.8
[0:02:12]  * [new ref]               refs/branch-heads/4.9         -> branch-heads/4.9
[0:02:12]  * [new ref]               refs/branch-heads/5.0         -> branch-heads/5.0
[0:02:12]  * [new ref]               refs/branch-heads/5.1         -> branch-heads/5.1
[0:02:12]  * [new ref]               refs/branch-heads/5.2         -> branch-heads/5.2
[0:02:12]  * [new ref]               refs/branch-heads/5.3         -> branch-heads/5.3
[0:02:12]  * [new ref]               refs/branch-heads/5.4         -> branch-heads/5.4
[0:02:12]  * [new ref]               refs/branch-heads/5.5         -> branch-heads/5.5
[0:02:12]  * [new ref]               refs/branch-heads/5.6         -> branch-heads/5.6
[0:02:12]  * [new ref]               refs/branch-heads/5.7         -> branch-heads/5.7
[0:02:12]  * [new ref]               refs/branch-heads/5.8         -> branch-heads/5.8
[0:02:12]  * [new ref]               refs/branch-heads/5.9         -> branch-heads/5.9
[0:02:12]  * [new ref]               refs/branch-heads/6.0         -> branch-heads/6.0
[0:02:12]  * [new ref]               refs/branch-heads/6.1         -> branch-heads/6.1
[0:02:12]  * [new ref]               refs/branch-heads/6.2         -> branch-heads/6.2
[0:02:12]  * [new ref]               refs/branch-heads/6.3         -> branch-heads/6.3
[0:02:12]  * [new ref]               refs/branch-heads/experimental -> branch-heads/experimental
[0:02:12]  * [new ref]               refs/branch-heads/test-gnumbd -> branch-heads/test-gnumbd
[0:02:13] Checked out refs/remotes/origin/master to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch to
an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.
[0:02:13]
----------------------------------------
Error: 1> dependency url must be either a string, None, File() or From() instead of dict
Running: gclient config --spec 'solutions = [
  {
    "managed": False,
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 353, in <module>
    sys.exit(main())
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 348, in main
    return run(options, spec, root)
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 342, in run
    return checkout.init()
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8/builder.rb:109:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8/builder.rb:107:in `chdir'
	from /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8/builder.rb:107:in `setup_build_deps!'
	from /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8/builder.rb:63:in `build_libv8!'
	from /bundle/gems/libv8-5.3.332.38.5-x86_64-linux/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'
ERROR:  Error installing libv8-5.3.332.38.5-x86_64-linux.gem:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1
```

**Comment by ignisf** [comment] 2018-06-27 14:02
Duplicate of https://github.com/cowboyd/libv8/issues/259

**Closed** 2018-06-27 14:02 UTC
Labels: needs: investigation, os: linux
