### ISSUE TITLE
Failed to install v.6 on High Sierra (very slow install for v.5)

### ISSUE THREAD

**Issue by Fjan** [cowboyd/libv8#247] opened 2017-09-26 13:07 UTC
A straightforward `gem install libv8` fails on macOS High Sierra for the most recent version of the gem (6.0) and a few earlier versions I tried (5.9, 5.3). It appears to compile but never completes. Curiously, it does install version 3.16 (as part of RubyRacer).

**Comment by ignisf** [comment] 2017-09-26 13:17
Hi,

So, a standard compilation from source of the libv8 6+ gem takes around 20 minutes on macOS =(. Travis CI have not as of yet released High Sierra build hosts on which I can build binaries. Could you check in your processes if the gem is in fact compiling?

**Comment by Fjan** [comment] 2017-09-26 14:54
Hmm, that could explain it, this was on an oldish Macbook Air, so I could have been too impatient. I'll give it another go tonight.

**Comment by kusold** [comment] 2017-09-26 17:27
Adding a data point:
The build succeeded for me after an excruciating wait of 27 minutes.

Ruby 2.4.2
libv8 5.9.211.38.1

![screen shot 2017-09-26 at 11 24 08 am](https://user-images.githubusercontent.com/509966/30874339-3cd06d1a-a2ad-11e7-9b2f-fd6bf9601217.png)

**Comment by Fjan** [comment] 2017-09-26 17:38
Yes, I can confirm, the install does eventually install for version 5, it appears I was not patient enough. For version 6 it still errors our right away.
```
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /Users/jmfaber/.rvm/gems/ruby-2.4.1/gems/libv8-6.0.286.54.1/ext/libv8
/Users/jmfaber/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20170926-606-ylqfj0.rb extconf.rb
creating Makefile
fatal: Not a git repository (or any of the parent directories): .git
/Users/jmfaber/.rvm/gems/ruby-2.4.1/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to checkout source for v8 6.0.286.54 (RuntimeError)
	from /Users/jmfaber/.rvm/gems/ruby-2.4.1/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:115:in `chdir'
```
I'll update the issue description to make it more clear. I'm fine with using v5, so you can close this if you want, or leave it open as a reference for people looking to use v6

**Comment by ignisf** [comment] 2017-09-26 20:51
Thank you all, will release binaries as soon as Travis starts allowing high sierra builds.

@Fjan, the issue you're experiencing with 6 is https://github.com/cowboyd/libv8/issues/246. Will try to make time to fix it.

**Comment by kbarrette** [comment] 2017-10-03 17:24
@ignisf any update on binaries for High Sierra?

**Comment by douglas** [comment] 2017-10-12 16:12
Hey @kbarrette,

If you need binaries for High Sierra or if you want/prefer to build them yourself, there is some instructions in [this thread](https://github.com/cowboyd/libv8/issues/248).

**Comment by ignisf** [comment] 2017-10-23 20:16
this issue is a duplicate of 246

**Comment by ignisf** [comment] 2017-10-23 20:17
Duplicate of 246

**Closed** 2017-10-23 21:48 UTC
Labels: os: osx
