### ISSUE TITLE
Performance regression in 3.16.14 series?

### ISSUE THREAD

**Issue by ewoodh2o** [cowboyd/libv8#150] opened 2014-11-05 19:15 UTC
We upgraded libv8 to the 3.16.14 series last week and started seeing significantly slower asset compilation times (through Uglifier) compared to v3.11.8.17.  I came at this through Rails' Asset Pipeline, so I'm way in the weeds here and don't know if it's libv8 or V8 itself, but thought I'd ask here to see if anyone had similar experiences.

This doesn't seem to affect times on my dev machine (OS X 10.10, Intel Core i7), but it's between 2x and 5x slower on our production servers (Scientific Linux 6.5, AMD).  Seems to be worse for larger files (obviously in strict wall-clock time, but also closer to 5x+ slower on the big files).

Benchmarks for `Uglifier.compile()`, which is just the easiest way I know how to test:

***libv8-3.11.8.17-x86_64-linux***

```
Compiling bootstrap.js (62kb, not minified)
  0.700000   0.030000   0.730000 (  0.721680)
  0.670000   0.030000   0.700000 (  0.688308)

Compiling highcharts.js (496kb, not minified)
  4.510000   0.040000   4.550000 (  4.499848)
  4.250000   0.030000   4.280000 (  4.238179)

Compiling jquery-1.8.1.min.js (93kb, already minified)
  2.630000   0.040000   2.670000 (  2.639083)
  2.540000   0.030000   2.570000 (  2.548431)

Compiling jquery-ui-1.8.23.min.js (205kb, already minified)
  3.320000   0.070000   3.390000 (  3.345508)
  3.360000   0.070000   3.430000 (  3.382746)

Compiling application.js (900kb, mixed)
 15.020000   0.300000  15.320000 ( 15.129480)
 16.170000   0.180000  16.350000 ( 16.162925)
```

***libv8-3.16.14.3-x86_64-linux***

```
Compiling bootstrap.js (62kb, not minified)
  0.980000   0.010000   0.990000 (  0.976608)
  0.860000   0.020000   0.880000 (  0.865921)

Compiling highcharts.js (496kb, not minified)
  8.720000   0.080000   8.800000 (  8.736296)
  7.230000   0.060000   7.290000 (  7.230722)

Compiling jquery-1.8.1.min.js (93kb, already minified)
  4.110000   0.080000   4.190000 (  4.153838)
  3.830000   0.030000   3.860000 (  3.830293)

Compiling jquery-ui-1.8.23.min.js (205kb, already minified)
  7.260000   0.060000   7.320000 (  7.273115)
  6.580000   0.030000   6.610000 (  6.579161)

Compiling application.js (900kb, mixed)
 82.280000   0.190000  82.470000 ( 82.314145)
 87.490000   0.220000  87.710000 ( 87.526244)
```

Anyone experiencing anything similar, or have any ideas on what might cause this?

**Comment by beekermememe** [comment] 2015-02-04 02:57
+1 on this, We are going from 5 minute deploys up to 18 minutes when deploying to C1 large instances
Rails 3.2.21. We are running a SPA so a good few JS files.

**Comment by pseidemann** [comment] 2015-07-06 19:23
+1

**Comment by stefankaiser** [comment] 2015-09-09 16:00
+1

**Comment by SamSaffron** [comment] 2016-05-02 08:08
I am going to have to debug this, as it stands it takes us 12 seconds to simply run our JS snippets through babel to build application.js, this feels way too long. 

I completely eliminated the ruby racer from our assets minification pipeline due to this huge performance hole. Going to work on some simpler repros this week, but this issue does need more attention.

**Comment by ignisf** [comment] 2016-05-02 11:03
A reproduction would help. Let me know if I can help in some way. Unfortunately profiling c++ is a bit out of my league or I would have taken a crack at this.

**Comment by bf4** [comment] 2016-05-02 13:40
@ewoodh2o what's in your test.rb?

**Comment by ignisf** [comment] 2016-05-02 14:24
I fear that this is a regression in the upstream code itself. If that proves to be the case, we might have to do one of the following things to get around the issue:

* dig up what exactly is causing the slowdown and create a patch or backport one from upstream
* wait up [until TRR gains support for new v8 APIs](https://github.com/cowboyd/therubyracer/pull/348) and roll out a new version
* create a new gem that only provides the subset of TRR's functionality necessary for asset generation through execjs to alleviate the dependency on v8's APIs and consequently ease updating to new versions of v8.

In any case, pinpointing the culprit is essential.

**Comment by SamSaffron** [comment] 2016-05-04 07:32
I started working on this ... 

I am making opening moves on building the world's most minimal ruby racer that links against latest v8:

https://github.com/SamSaffron/mini_racer

Performance is significantly better for uglification:

```
ruby uglify_mini_racer.rb app.js 
12.26s user 0.55s system 103% cpu 12.386 total

sam@ubuntu measure_v8 % time uglifyjs app.js 
4.44s user 0.18s system 103% cpu 4.454 total

sam@ubuntu measure_v8 % time ruby uglify.rb app.js
144.76s user 0.37s system 100% cpu 2:24.83 total
```

So there you are, exact same args as https://github.com/lautis/uglifier uses except that instead of taking 144 seconds for our app.js it takes 12. 

I am still very uncomfortable with node being this much faster and think a lot of this is due to the wrapping and es5 shims etc that uglifier gem adds will continue to investigate

uglify mini racer code
https://gist.github.com/SamSaffron/2ecc595349d96b572adf2b7c0b69448f

uglify ruby racer code
https://gist.github.com/SamSaffron/336c4bb73c6ea6ca071dba7455af8cbf

our gigantic already minified application js file I was testing with
https://gist.github.com/SamSaffron/148dfd50ecb63296040c4baad2ff34a7

**Comment by ignisf** [comment] 2016-05-04 08:14
Are you running this on Linux or on OS X? Keep in mind that I specifically disabled link-time optimisations on Linux as the build system was trying to run an ld.gold binary it had pulled and was failing.

**Comment by SamSaffron** [comment] 2016-05-04 08:19
Running this on Linux x64, perhaps it is those missing optimisations, will try with a "bring my own" libv8 tomorrow

**Comment by SamSaffron** [comment] 2016-05-05 09:15
no luck finding my missing 20% or so of perf, still @ignisf  a new libv8 gem would be mighty welcome even with this performance weirdness

**Comment by ignisf** [comment] 2016-05-05 11:30
I have a few nits to pick and will push a 5.0 version

**Comment by SamSaffron** [comment] 2016-05-05 23:25
@igas awesome! 

Be sure to pick latest stable from https://omahaproxy.appspot.com/ might as well package the latest stable version of v8

**Comment by ignisf** [comment] 2016-05-05 23:53
k, sure

**Comment by SamSaffron** [comment] 2016-05-08 13:52
@ignisf I just noticed I had to add:

```
$LDFLAGS.insert 0, " -stdlib=libstdc++ " if RUBY_PLATFORM =~ /darwin/ 
```

To work around a linker issue on mac turns out it links to libc++ by default or something, be sure to do a --pre release prior to doing a stable one so I can confirm mini racer compiles right

**Comment by ignisf** [comment] 2016-05-13 01:08
@SamSaffron are you by any chance hitting this issue: https://github.com/cowboyd/libv8/issues/202?

**Comment by SamSaffron** [comment] 2016-05-13 01:10
I was able to install fine on my osx but had to upgrade xcode to latest
first to get latest clang

**Comment by ignisf** [comment] 2016-05-15 15:27
For the record, here are results from running mini_racer's `benchmarks/bench_uglify.rb`:

| Runtime  | discourse_app.js | discourse_app_minified.js | discourse_app.js twice on 2 threads |
| --- | ---: | ---: | ---: |
| mini_racer  | 14496.41 ms | 18417.71 ms | 16932.05 ms |
| node  | 18518.89 ms | 25905.57 ms | 21642.31 ms |
| therubyracer | 187749.27 ms | 203036.86 ms | 507423.35 ms |

![chart](https://cloud.githubusercontent.com/assets/1153188/15275075/a93c5ed0-1aca-11e6-89e2-1aa180654941.png)

Will keep this issue open for now and hopefully close it after TRR is updated.

**Comment by coding-horror** [comment] 2016-05-15 23:12
Wow an exponential scale eh? :)

**Comment by ignisf** [comment] 2016-05-15 23:20
:disappointed:

**Comment by SamSaffron** [comment] 2016-05-16 03:53
This does illustrate a huge issue with exponential scale graphs :) 

![image](https://cloud.githubusercontent.com/assets/5213/15279913/3d12ab8a-1b6d-11e6-91d5-afc02cfdf2f9.png)

I would really like to rerun these numbers on Linux x64 comparing GCC vs clang compiled libv8 and mini_racer, I am very curious to see the performance difference

**Comment by ignisf** [comment] 2016-05-16 04:08
You should be able to do this by locking the version [to the source release](https://github.com/cowboyd/libv8/#versioning) and [configuring a compiler](https://github.com/cowboyd/libv8/#bring-your-own-compiler). One thing to note is that at least from the build guide it seems like clang is the preferred compiler for v8.

I don't expect there to be any major differences in performance just solely based on compiler choice, though. What could lead to a performance boost would be enabling link-time optimisations. I have not looked into that yet, though I think there's support for this in v8's build system.

**Comment by ignisf** [comment] 2016-05-16 04:29
I am really not sure we should just flick on LTO :D

![kkj3bvg](https://cloud.githubusercontent.com/assets/1153188/15280308/d867dbae-1b37-11e6-805b-16bebbb3f570.png)

**Comment by ignisf** [comment] 2016-05-16 05:19
Peak memory used for linking with lto on one make job is around 3,5512 GB. The produced binary gem archive is 275 MB.

It seems that the LTO is enabled automatically when linking the mini_racer_extension.so.

Could not benchmark because invoking the benchmark script causes a segfault. LTO-enabled branch can be found here: https://github.com/cowboyd/libv8/tree/lto

**Comment by SamSaffron** [comment] 2016-05-16 05:48
phoronix had some pretty mixed results with lto ..
http://www.phoronix.com/scan.php?page=article&item=gcc_471_lto&num=3

I mentioned the clang tests cause another bench I have has node clocking
20% faster so I am curious if this is the compilation of something
internal.

**Comment by SamSaffron** [comment] 2016-06-09 22:40
I think it is fine to close this for now, nothing more for libv8 to do in this regard

**Closed** 2016-06-10 05:24 UTC
Labels: status: blocked, type: bug

**Comment by ignisf** [comment] 2016-06-15 15:20
![babel obg](https://cloud.githubusercontent.com/assets/1153188/16085742/bf376450-3325-11e6-85b4-e511a00ce6e1.png)
![exec](https://cloud.githubusercontent.com/assets/1153188/16085744/c1279780-3325-11e6-940b-d108c363d5d0.png)
